apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "10.24.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      replicas: 1
    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 443
        expose: true
        exposedPort: 443
        protocol: TCP
    persistence:
      enabled: true
      size: 1Gi
    metrics:
      prometheus:
        enabled: true
    serviceMonitor:
      enabled: true
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - "--api.dashboard=true"
      - "--providers.kubernetescrd.allowcrossnamespace=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    service:
      type: LoadBalancer
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi" 