apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.6.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      serverPort: 3101
      lokiAddress: http://loki:3100/loki/api/v1/push
      snippets:
        scrapeConfigs:
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_kubernetes_io_config_mirror]
                action: drop
                regex: true
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                target_label: app
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
                target_label: instance
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
                target_label: component
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_managed_by]
                target_label: managed_by
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_part_of]
                target_label: part_of
    serviceMonitor:
      enabled: true